require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
--[[ require "user.nvim-navic" ]]
require "user.barbecue"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.nvim-tree"
--[[ require "user.bufferline" ]]
require "user.toggleterm"
require "user.lualine"
require "user.hop"
-- require "user.indentline"
require "user.project"
require "user.gitsigns"
require "user.neoscroll"
require "user.dashboard-nvim"
require "user.colorizer"
require "user.ufo"
